### ISSUE TITLE
I cannot install this plugin

### ISSUE THREAD

**Issue by jafamo** [NateWr/cacheBuster#2]
Hi, @NateWr ,

I am using ojs_3_1_4 and I would like to install this plugin.

I downloaded from "git clone" and I changed the permissions on my ojs installation.(apache)
My error_log:
```
[cgi:error] [pid 29442] [client 192.94.163.143:35270] AH01215: PHP Fatal error:  Call to undefined method Application::get() in ojs/plugins/generic/cacheBuster/CacheBusterPlugin.inc.php on line 21
```

Regards, 
xavi

**Comment by NateWr** [comment]
I've just pushed up a `stable-3_1_2` branch which should work with 3.1.1-4 as well:

https://github.com/NateWr/cacheBuster/tree/stable-3_1_2

Try doing another fetch and checking out that branch:

```
git fetch origin
git checkout stable-3_1_2
```

**Comment by jafamo** [comment]
Thank you !!!

Regards,
xavi
